name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        pip install uv

    - name: Create virtual environment
      run: |
        uv venv

    - name: Activate virtual environment
      run: |
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt
        uv pip install pytest pytest-cov ruff
        
    - name: Run tests
      run: |
        python -m pytest
        
    - name: Lint with ruff
      run: |
        ruff check . 