name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        pip install uv

    - name: Create and activate virtual environment
      run: |
        uv venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Verify virtual environment
      run: |
        which python
        python -V

    - name: Install pip in virtual environment
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py
        rm get-pip.py

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install pytest pytest-cov ruff
        
    - name: Run tests
      run: |
        python -m pytest
        
    - name: Lint with ruff
      run: |
        ruff check . --exclude get-pip.py 